# Generated by Django 4.2.9 on 2024-02-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muscle_group',
            name='large_group',
            field=models.CharField(choices=[('legs', 'Legs'), ('shoulders', 'Shoulders'), ('back', 'Back'), ('abs', 'Abs')], default='none', max_length=32),
        ),
    ]
