# Generated by Django 4.2.9 on 2024-02-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='repetition',
            field=models.CharField(max_length=255),
        ),
    ]
