# Generated by Django 4.2.9 on 2024-02-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_exercise_category_and_more'),
        ('workouts', '0002_alter_workoutexercise_repetition'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(through='workouts.WorkoutExercise', to='exercises.exercise'),
        ),
    ]
